# Divi Hub Service
apiVersion: v1
kind: Service
metadata:
  name: hub-server
  namespace: dh-app
spec:
  selector:
    app: hub-server
  ports:
    - port: 9000
      targetPort: 9000
      name: fastcgi
