# Divi Hub Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
      name: http
---

{{- if .Values.SERVICE_MONITOR_ENABLED }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - path: /metrics
      port: http
      authorization:
        type: Bearer
        credentials:
          name: secrets
          key: DIVI_METRICS_ENDPOINT_TOKEN
---

{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        redis-client: 'true'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Release.Name }}
              namespaces:
                - {{ .Release.Namespace }}
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cloud-screenshot
              namespaces:
                - dc-screenshot
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HUB_SERVER_PATH
              value: {{ .Values.HUB_SERVER_PATH | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
            - name: HUB_SERVER_REPO_URL
              value: {{ .Values.HUB_SERVER_REPO_URL | squote }}
            - name: IMAGE_VERSION
              value: {{ .Values.HUB_SERVER_VERSION | squote }}
            - name: HUB_SERVER_INIT
              value: '1'
            - name: PHP_OPCACHE_FILE_CACHE
              value: {{ ternary "/var/cache/php" "" (eq "production" .Values.HUB_SERVER_ENV) | squote }}
            - name: PHP_OPCACHE_VALIDATE_TIMESTAMPS
              value: {{ ternary "false" "true" (eq "production" .Values.HUB_SERVER_ENV) | squote }}
          image: {{ .Values.HUB_SERVER_IMAGE | squote }}
          command: [ '/etc/cont-init.d/init' ]
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: '4'
              memory: 2G
          volumeMounts:
            - name: workspace
              mountPath: /srv
            - name: config
              mountPath: /config
              readOnly: true

      containers:
        - name: app
          image: {{ .Values.HUB_SERVER_IMAGE | squote }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HUB_SERVER_PATH
              value: {{ .Values.HUB_SERVER_PATH | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
            - name: PHP_MEMORY_LIMIT
              value: {{ .Values.PHP_MEMORY_LIMIT | squote }}
            - name: PHP_OPCACHE_FILE_CACHE
              value: ""
            - name: PHP_OPCACHE_VALIDATE_TIMESTAMPS
              value: "1"
          livenessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.HUB_SERVER_PATH }}/public/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 30
          ports:
            - name: fastcgi
              containerPort: 9000
          readinessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.HUB_SERVER_PATH }}/public/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 5000m
              memory: 2G
          startupProbe:
            exec:
              command:
                - cat
                - {{ .Values.HUB_SERVER_PATH }}/public/healthz.php
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: workspace
              mountPath: /srv
            - name: config
              mountPath: /config
              readOnly: true
        - name: nginx
          image: 'nginx:1.27.5-alpine'
          livenessProbe:
            httpGet:
              path: /time
              port: 80
            periodSeconds: 30
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /time
              port: 80
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: workspace
              mountPath: /srv
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
              subPath: nginx.conf

{{ range $_, $index := untilStep 1 (int .Values.HUB_SERVER_WORKERS) 1 }}
{{ include "hub.container.worker" (dict "Values" $.Values "index" $index) }}
{{ end }}

      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
      volumes:
        - name: workspace
{{- if .Values.WORKSPACE_HOST_PATH }}
          hostPath:
            path: {{ .Values.WORKSPACE_HOST_PATH | squote }}
            type: DirectoryOrCreate
{{- else }}
          emptyDir: {}
{{- end }}
        - name: config
          secret:
            secretName: secrets
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
