apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote }}
  .env: |
    APP_ENV={{ .Values.HUB_SERVER_ENV | squote }}
    APP_URL='https://{{ .Values.VIRTUAL_HOST }}'
    DIVI_HUB_ENDPOINT={{ .Values.DIVI_HUB_ENDPOINT | squote }}
    DIVI_HUB_WEBSITES_QUEUE_SIZE={{ .Values.DIVI_HUB_WEBSITES_QUEUE_SIZE | squote }}
    DIVI_HUB_IP_ADDRESS={{ .Values.DIVI_HUB_IP_ADDRESS | squote }}
    DIVI_HUB_PRIVATE_KEY_64={{ .Values.DIVI_HUB_PRIVATE_KEY_64 | b64enc | squote }}
    DIVI_HUB_PUBLIC_KEY_SERVER='https://{{ .Values.VIRTUAL_HOST }}/public-key'
    DIVI_HUB_TIME_SERVER='https://{{ .Values.VIRTUAL_HOST }}/time'
    HUB_SERVER_PATH={{ .Values.HUB_SERVER_PATH | squote }}
    HUB_SERVER_REPO_URL={{ .Values.HUB_SERVER_REPO_URL | squote }}
    IMAGE_VERSION={{ .Values.HUB_SERVER_VERSION | squote }}
    REDIS_HOST={{ .Values.REDIS_HOSTNAME | squote }}
    REDIS_SENTINEL_HOST={{ .Values.REDIS_HOSTNAME | squote }}
    REDIS_SENTINEL_SERVICE={{ .Values.REDIS_SENTINEL_SERVICE | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}

