apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote }}
  .env: |
    API_EXPECTED_REQUEST_SECRET={{ .Values.API_EXPECTED_REQUEST_SECRET | squote }}
    APP_ENV={{ .Values.HUB_SERVER_ENV | squote }}
    APP_URL='https://{{ .Values.VIRTUAL_HOST }}'
    DASH_EXPECTED_REQUEST_SECRET={{ .Values.DASH_EXPECTED_REQUEST_SECRET | squote }}
    DIVI_HUB_API_LIVE_SERVER='https://{{ .Values.VIRTUAL_HOST }}'
    DIVI_HUB_WEBSITES_QUEUE_SIZE={{ .Values.DIVI_HUB_WEBSITES_QUEUE_SIZE | squote }}
    DIVI_HUB_IP_ADDRESS={{ .Values.DIVI_HUB_IP_ADDRESS | squote }}
    DIVI_HUB_PRIVATE_KEY_64={{ .Values.DIVI_HUB_PRIVATE_KEY_64 | b64enc | squote }}
    DIVI_HUB_SERVER_URL={{ .Values.DIVI_HUB_SERVER_URL | squote }}
    HORIZON_ALLOWED_IPS={{ .Values.HORIZON_ALLOWED_IPS | squote }}
    HUB_SERVER_PATH={{ .Values.HUB_SERVER_PATH | squote }}
    HUB_SERVER_REPO_URL={{ .Values.HUB_SERVER_REPO_URL | squote }}
    IMAGE_VERSION={{ .Values.HUB_SERVER_VERSION | squote }}
    JWT_AUTH_PUBLIC_KEY={{ .Values.JWT_AUTH_PUBLIC_KEY | squote }}
    REDIS_HOST={{ .Values.REDIS_HOSTNAME | squote }}
    REDIS_SENTINEL_HOST={{ .Values.REDIS_HOSTNAME | squote }}
    REDIS_SENTINEL_SERVICE={{ .Values.REDIS_SENTINEL_SERVICE | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}

