apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | quote }}
  .env: |
    ALLOWED_IPS={{ .Values.ALLOWED_IPS | quote }}
    AUTH_SERVER_ENV={{ .Values.AUTH_SERVER_ENV | quote }}
    AUTH_SERVER_PATH={{ .Values.INSTALL_PATH | quote }}
    AUTH_SERVER_PORT={{ .Values.AUTH_SERVER_PORT }}
    AUTH_SERVER_REPO_URL={{ .Values.AUTH_SERVER_REPO_URL | quote }}
    AUTH_SERVER_SECRET={{ .Values.AUTH_SERVER_SECRET | quote }}
    IMAGE_VERSION={{ .Values.AUTH_SERVER_VERSION | quote }}
    REDIS_HOSTNAME={{ .Values.REDIS_HOSTNAME | quote }}
    REDIS_NAME={{ .Values.REDIS_NAME | quote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | quote }}
    JWT_PRIVATE_KEY={{ .Values.JWT_PRIVATE_KEY | b64enc | quote }}
    JWT_PUBLIC_KEY={{ .Values.JWT_PUBLIC_KEY | b64enc | quote }}
    MAILGUN_API_KEY={{ .Values.MAILGUN_API_KEY | quote }}
    MAILGUN_API_URL={{ .Values.MAILGUN_API_URL | quote }}

