apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote }}
  .env: |
    AUTH_SERVER_ENV={{ .Values.AUTH_SERVER_ENV | squote }}
    AUTH_SERVER_PATH={{ .Values.INSTALL_PATH | squote }}
    AUTH_SERVER_PORT={{ .Values.AUTH_SERVER_PORT }}
    AUTH_SERVER_REPO_URL={{ .Values.AUTH_SERVER_REPO_URL | squote }}
    IMAGE_VERSION={{ .Values.AUTH_SERVER_VERSION | squote }}
    JWT_PRIVATE_KEY={{ .Values.JWT_PRIVATE_KEY | b64enc | squote }}
    REDIS_HOSTNAME={{ .Values.REDIS_HOSTNAME | squote }}
    REDIS_NAME={{ .Values.REDIS_NAME | squote }}
    SWAGGER_ALLOWED_IPS={{ .Values.SWAGGER_ALLOWED_IPS | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}

