apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote }}
  .env: |-
{{- required "ENV_FILE is required" .Values.ENV_FILE | nindent 4 }}
