apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote }}
  .env: |
    ADMINS={{ .Values.ADMINS | squote }}
    DIVI_ZIP={{ .Values.DIVI_ZIP | squote }}
    DS_SERVER_ENV={{ .Values.DS_SERVER_ENV | squote }}
    DS_SERVER_PATH={{ .Values.INSTALL_PATH | squote }}
    DS_SERVER_PORT={{ .Values.DS_SERVER_PORT }}
    DS_SERVER_REPO_URL={{ .Values.DS_SERVER_REPO_URL | squote }}
    IMAGE_VERSION={{ .Values.DS_SERVER_VERSION | squote }}
    JWT_PUBLIC_KEY={{ .Values.JWT_PUBLIC_KEY | b64enc | squote }}
    JWT_PUBLIC_KEY_AUTH={{ .Values.JWT_PUBLIC_KEY_AUTH | b64enc | squote }}
    JWT_TOKEN={{ .Values.JWT_TOKEN | squote }}
    PRESSABLE_API_URL={{ .Values.PRESSABLE_API_URL | squote }}
    PRESSABLE_CLIENT_ID={{ .Values.PRESSABLE_CLIENT_ID | squote }}
    PRESSABLE_CLIENT_SECRET={{ .Values.PRESSABLE_CLIENT_SECRET | squote }}
    PRESSABLE_PRIVATE_KEY={{ .Values.PRESSABLE_PRIVATE_KEY | b64enc | squote }}
    PRESSABLE_SHARED_KEY={{ .Values.PRESSABLE_SHARED_KEY | squote }}
    REDIS_HOSTNAME={{ .Values.REDIS_HOSTNAME | squote }}
    REDIS_NAME={{ .Values.REDIS_NAME | squote }}
    SUPPORT_USERS={{ .Values.SUPPORT_USERS | squote }}
    SWAGGER_ALLOWED_IPS={{ .Values.SWAGGER_ALLOWED_IPS | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}

