# Divi Demo Service
apiVersion: v1
kind: Service
metadata:
  name: d5-demo-server
  namespace: d5d-app
spec:
  selector:
    app: d5-demo-server
  ports:
    - port: 9000
      targetPort: 9000
      name: fastcgi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: d5-demo-server
  namespace: d5d-app
  labels:
    app: d5-demo-server
spec:
  replicas: {{ .Values.REPLICAS }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: d5-demo-server
  template:
    metadata:
      labels:
        app: d5-demo-server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx
              namespaces:
                - ingress-nginx
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - d5-demo-server
              namespaces:
                - d5d-app
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEMO_SERVER_PATH
              value: {{ .Values.INSTALL_PATH | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
            - name: DEMO_SERVER_REPO_URL
              value: {{ .Values.DEMO_SERVER_REPO_URL | squote }}
            - name: IMAGE_VERSION
              value: {{ .Values.DEMO_SERVER_VERSION | squote }}
            - name: DEMO_SERVER_INIT
              value: '1'
            - name: DIVI_VERSION
              value: {{ .Values.DIVI_VERSION | squote }}
            - name: ET_API_KEY
              value: {{ .Values.ET_API_KEY | squote }}
            - name: ET_API_USER
              value: {{ .Values.ET_API_USER | squote }}
            - name: PHP_OPCACHE_FILE_CACHE
              value: {{ ternary "/var/cache/php" "" (eq "production" .Values.WP_ENV) | squote }}
            - name: PHP_OPCACHE_VALIDATE_TIMESTAMPS
              value: {{ ternary "false" "true" (eq "production" .Values.WP_ENV) | squote }}
          image: {{ .Values.DEMO_SERVER_IMAGE | squote }}
          command: ['/etc/cont-init.d/init']
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: '4'
              memory: 2G
          volumeMounts:
            - name: wordpress
              mountPath: /srv
            - name: demo-mysql
              mountPath: /var/lib/mysql
            - name: demo-redis
              mountPath: /var/lib/redis
            - name: config
              mountPath: /config
              readOnly: true
      containers:
        - name: app
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEMO_SERVER_PATH
              value: {{ .Values.INSTALL_PATH | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
            - name: DEMO_SERVER_REPO_URL
              value: {{ .Values.DEMO_SERVER_REPO_URL | squote }}
            - name: IMAGE_VERSION
              value: {{ .Values.DEMO_SERVER_VERSION | squote }}
            - name: PHP_OPCACHE_FILE_CACHE
              value: {{ ternary "/var/cache/php" "" (eq "production" .Values.WP_ENV) | squote }}
            - name: PHP_OPCACHE_VALIDATE_TIMESTAMPS
              value: {{ ternary "false" "true" (eq "production" .Values.WP_ENV) | squote }}
            - name: DIVI_VERSION
              value: {{ .Values.DIVI_VERSION | squote }}
            - name: DEMO_SERVER_PHP
              value: '1'

          image: {{ .Values.DEMO_SERVER_IMAGE | squote }}
          livenessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.INSTALL_PATH }}/web/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 30
          ports:
            - name: fastcgi
              containerPort: 9000
          readinessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.INSTALL_PATH }}/web/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: '5'
              memory: 2G
          startupProbe:
            exec:
              command:
                - cat
                - {{ .Values.INSTALL_PATH }}/web/healthz.php
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: wordpress
              mountPath: /srv
            - name: config
              mountPath: /config
              readOnly: true

        - name: database
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEMO_SERVER_PATH
              value: {{ .Values.INSTALL_PATH | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
            - name: DEMO_SERVER_REPO_URL
              value: {{ .Values.DEMO_SERVER_REPO_URL | squote }}
            - name: IMAGE_VERSION
              value: {{ .Values.DEMO_SERVER_VERSION | squote }}
            - name: PHP_OPCACHE_FILE_CACHE
              value: {{ ternary "/var/cache/php" "" (eq "production" .Values.WP_ENV) | squote }}
            - name: PHP_OPCACHE_VALIDATE_TIMESTAMPS
              value: {{ ternary "false" "true" (eq "production" .Values.WP_ENV) | squote }}
            - name: DEMO_SERVER_DATABASE
              value: '1'

          image: {{ .Values.DEMO_SERVER_IMAGE | squote }}
          livenessProbe:
            exec:
              command:
                - 'mysqladmin'
                - 'ping'
            initialDelaySeconds: 5
            periodSeconds: 20
          ports:
            - name: mysql
              containerPort: 3306
          readinessProbe:
            exec:
              command:
                - 'mysqladmin'
                - 'ping'
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: '2'
              memory: 1G
          startupProbe:
            exec:
              command:
                - 'mysqladmin'
                - 'ping'
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: wordpress
              mountPath: /srv
            - name: demo-mysql
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /config
              readOnly: true

        - name: redis
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEMO_SERVER_PATH
              value: {{ .Values.INSTALL_PATH | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
            - name: DEMO_SERVER_REPO_URL
              value: {{ .Values.DEMO_SERVER_REPO_URL | squote }}
            - name: IMAGE_VERSION
              value: {{ .Values.DEMO_SERVER_VERSION | squote }}
            - name: PHP_OPCACHE_FILE_CACHE
              value: {{ ternary "/var/cache/php" "" (eq "production" .Values.WP_ENV) | squote }}
            - name: PHP_OPCACHE_VALIDATE_TIMESTAMPS
              value: {{ ternary "false" "true" (eq "production" .Values.WP_ENV) | squote }}
            - name: DEMO_SERVER_REDIS
              value: '1'

          image: {{ .Values.DEMO_SERVER_IMAGE | squote }}
          livenessProbe:
            exec:
              command:
                - 'redis-cli'
                - 'ping'
            initialDelaySeconds: 5
            periodSeconds: 20
          ports:
            - name: mysql
              containerPort: 3306
          readinessProbe:
            exec:
              command:
                - 'redis-cli'
                - 'ping'
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: '2'
              memory: 1G
          startupProbe:
            exec:
              command:
                - 'redis-cli'
                - 'ping'
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: wordpress
              mountPath: /srv
            - name: demo-redis
              mountPath: /var/lib/redis
            - name: config
              mountPath: /config
              readOnly: true

      volumes:
        - name: wordpress
          hostPath:
            path: /srv
            type: DirectoryOrCreate
        - name: demo-mysql
          hostPath:
            path: /var/lib/demo-mysql
            type: DirectoryOrCreate
        - name: demo-redis
          hostPath:
            path: /var/lib/demo-redis
            type: DirectoryOrCreate
        - name: config
          secret:
            secretName: secrets
