apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: d5-demo-server
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: {{ .Values.INGRESS_CLASS_NAME | quote }}
  tls:
    - hosts:
        - {{ .Values.VIRTUAL_HOST }}
      secretName: d5-demo-server-tls
  rules:
    - host: {{ .Values.VIRTUAL_HOST }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: d5-demo-server
                port:
                  name: http
