apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: d5d-app
stringData:
  ADMIN_USER: {{ .Values.ADMIN_USER | squote }}
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD | squote}}
  ADMIN_EMAIL: {{ .Values.ADMIN_EMAIL | squote }}
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote}}
  UPLOADS_ZIP_URL: {{ .Values.UPLOADS_ZIP_URL | squote }}
  .env: |
    AUTH_KEY={{ .Values.AUTH_KEY | squote }}
    AUTH_SALT={{ .Values.AUTH_SALT | squote }}
    DEMO_SERVER_PATH={{ .Values.INSTALL_PATH | squote }}
    DEMO_SERVER_REPO_URL={{ .Values.DEMO_SERVER_REPO_URL | squote }}
    DB_HOST={{ .Values.DB_HOST | squote }}
    DB_NAME={{ .Values.DB_NAME | squote }}
    DB_PASSWORD={{ .Values.DB_PASSWORD | squote }}
    DB_PREFIX={{ .Values.DB_PREFIX | squote }}
    DB_USER={{ .Values.DB_USER | squote }}
    IMAGE_VERSION={{ .Values.DEMO_SERVER_VERSION | squote }}
    LOGGED_IN_KEY={{ .Values.LOGGED_IN_KEY | squote }}
    LOGGED_IN_SALT={{ .Values.LOGGED_IN_SALT | squote }}
    NONCE_KEY={{ .Values.NONCE_KEY | squote }}
    NONCE_SALT={{ .Values.NONCE_SALT | squote }}
    SECURE_AUTH_KEY={{ .Values.SECURE_AUTH_KEY | squote }}
    SECURE_AUTH_SALT={{ .Values.SECURE_AUTH_SALT | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}
    WP_DEBUG_LOG=true
    WP_ENV={{ .Values.WP_ENV | squote }}
    WP_HOME={{ .Values.WP_HOME | squote }}
    WP_SITEURL={{ .Values.WP_SITEURL | squote }}

