apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-fcgi-params
  namespace: {{ .Release.Namespace }}
data:
  SCRIPT_FILENAME:   $document_root$fastcgi_script_name
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: FCGI
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/fastcgi-index: index.php
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: {{ .Release.Namespace }}/ingress-fcgi-params
    nginx.ingress.kubernetes.io/limit-connections: "8"
    nginx.ingress.kubernetes.io/limit-rps: "8"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-req-status-code: "429"
    nginx.ingress.kubernetes.io/limit-conn-status-code: "429"
    nginx.ingress.kubernetes.io/use-regex: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.VIRTUAL_HOST }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.VIRTUAL_HOST }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: fastcgi
