# Cloud Server Service
apiVersion: v1
kind: Service
metadata:
  name: cloud-server
  namespace: cloud-server
spec:
  selector:
    app: cloud-server
  ports:
    - port: 9000
      targetPort: 9000
      name: fastcgi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-server
  namespace: cloud-server
  labels:
    app: cloud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-server
  template:
    metadata:
      labels:
        app: cloud-server
    spec:
      containers:
        - name: cloud-server
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLOUD_SERVER_PATH
              value: '{{ .Values.INSTALL_PATH }}'
            - name: VIRTUAL_HOST
              value: '{{ .Values.VIRTUAL_HOST }}'
            - name: CLOUD_SERVER_REPO_URL
              value: '{{ .Values.CLOUD_SERVER_REPO_URL }}'
          image: '{{ .Values.CLOUD_SERVER_IMAGE }}'
          livenessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.INSTALL_PATH }}/web/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 30
          ports:
            - name: fastcgi
              containerPort: 9000
          readinessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.INSTALL_PATH }}/web/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 600Mi
          startupProbe:
            exec:
              command:
                - cat
                - {{ .Values.INSTALL_PATH }}/web/healthz.php
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: wordpress
              mountPath: /srv
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: wordpress
          hostPath:
            path: /srv
            type: DirectoryOrCreate
        - name: config
          secret:
            secretName: .env
