# Cloud Server Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
      name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Release.Name }}
              namespaces:
                - {{ .Release.Namespace }}
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cloud-screenshot
              namespaces:
                - dc-screenshot
              topologyKey: kubernetes.io/hostname
      containers:
        - name: cloud-server
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLOUD_SERVER_PATH
              value: {{ .Values.INSTALL_PATH | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
            - name: CLOUD_SERVER_REPO_URL
              value: {{ .Values.CLOUD_SERVER_REPO_URL | squote }}
            - name: IMAGE_VERSION
              value: {{ .Values.CLOUD_SERVER_VERSION | squote }}
            - name: PHP_MEMORY_LIMIT
              value: {{ .Values.PHP_MEMORY_LIMIT | squote }}
            - name: PHP_OPCACHE_FILE_CACHE
              value: {{ ternary "/var/cache/php" "" (eq "production" .Values.WP_ENV) | squote }}
            - name: PHP_OPCACHE_VALIDATE_TIMESTAMPS
              value: {{ ternary "false" "true" (eq "production" .Values.WP_ENV) | squote }}

          image: {{ .Values.CLOUD_SERVER_IMAGE | squote }}
          livenessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.INSTALL_PATH }}/web/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 30
          ports:
            - name: fastcgi
              containerPort: 9000
          readinessProbe:
            exec:
              command:
                - 'bash'
                - '-c'
                - 'SCRIPT_NAME=/healthz'
                - 'SCRIPT_FILENAME={{ .Values.INSTALL_PATH }}/web/healthz.php'
                - 'REQUEST_METHOD=GET'
                - 'cgi-fcgi'
                - '-bind'
                - '-connect'
                - '127.0.0.1:9000'
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 4000m
              memory: 3G
          startupProbe:
            exec:
              command:
                - cat
                - {{ .Values.INSTALL_PATH }}/web/healthz.php
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: wordpress
              mountPath: /srv
            - name: config
              mountPath: /config
              readOnly: true
        - name: nginx
          image: 'nginx:1.27.5-alpine'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 30
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: wordpress
              mountPath: /srv
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
              subPath: nginx.conf
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: wordpress
          emptyDir: {}
        - name: config
          secret:
            secretName: secrets
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
