# Cloud Server Service
apiVersion: v1
kind: Service
metadata:
  name: cloud-server
  namespace: cloud-server
spec:
  selector:
    app: cloud-server
  ports:
    - port: 9000
      targetPort: 9000
      name: fastcgi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-server
  namespace: cloud-server
  labels:
    app: cloud-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-server
  template:
    metadata:
      labels:
        app: cloud-server
    spec:
      containers:
        - name: cloud-server
          image: elegantthemes/cloud-server:{{ .Chart.appVersion }}
          ports:
            - name: fastcgi
              containerPort: 9000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 600Mi
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: workspace
          emptyDir: {}
        - name: config
          secret:
            secretName: wp-config
