apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: dc-app
stringData:
  ADMIN_USER: {{ .Values.ADMIN_USER }}
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD }}
  ADMIN_EMAIL: {{ .Values.ADMIN_EMAIL }}
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN }}
  .env: |
    AUTH_KEY='{{ .Values.AUTH_KEY }}'
    AUTH_SALT='{{ .Values.AUTH_SALT }}'
    DB_HOST='{{ .Values.DB_HOST }}'
    DB_NAME='{{ .Values.DB_NAME }}'
    DB_PASSWORD='{{ .Values.DB_PASSWORD }}'
    DB_PREFIX='{{ .Values.DB_PREFIX }}'
    DB_USER='{{ .Values.DB_USER }}'
    LOGGED_IN_KEY='{{ .Values.LOGGED_IN_KEY }}'
    LOGGED_IN_SALT='{{ .Values.LOGGED_IN_SALT }}'
    NONCE_KEY='{{ .Values.NONCE_KEY }}'
    NONCE_SALT='{{ .Values.NONCE_SALT }}'
    S3_BUCKET_CLOUD_ITEMS='{{ .Values.S3_BUCKET_CLOUD_ITEMS }}'
    S3_BUCKET_CLOUD_ITEMS_BACKUP_1='{{ .Values.S3_BUCKET_CLOUD_ITEMS_BACKUP_1 }}'
    S3_BUCKET_CLOUD_ITEMS_BACKUP_2='{{ .Values.S3_BUCKET_CLOUD_ITEMS_BACKUP_2 }}'
    S3_ENDPOINT_CLOUD_ITEMS='{{ .Values.S3_ENDPOINT_CLOUD_ITEMS }}'
    S3_ENDPOINT_CLOUD_ITEMS_BACKUP_1='{{ .Values.S3_ENDPOINT_CLOUD_ITEMS_BACKUP_1 }}'
    S3_ENDPOINT_CLOUD_ITEMS_BACKUP_2='{{ .Values.S3_ENDPOINT_CLOUD_ITEMS_BACKUP_2 }}'
    S3_KEY_CLOUD_ITEMS='{{ .Values.S3_KEY_CLOUD_ITEMS }}'
    S3_KEY_CLOUD_ITEMS_BACKUP_1='{{ .Values.S3_KEY_CLOUD_ITEMS_BACKUP_1 }}'
    S3_KEY_CLOUD_ITEMS_BACKUP_2='{{ .Values.S3_KEY_CLOUD_ITEMS_BACKUP_2 }}'
    S3_REGION_CLOUD_ITEMS='{{ .Values.S3_REGION_CLOUD_ITEMS }}'
    S3_REGION_CLOUD_ITEMS_BACKUP_1='{{ .Values.S3_REGION_CLOUD_ITEMS_BACKUP_1 }}'
    S3_REGION_CLOUD_ITEMS_BACKUP_2='{{ .Values.S3_REGION_CLOUD_ITEMS_BACKUP_2 }}'
    S3_SECRET_CLOUD_ITEMS='{{ .Values.S3_SECRET_CLOUD_ITEMS }}'
    S3_SECRET_CLOUD_ITEMS_BACKUP_1='{{ .Values.S3_SECRET_CLOUD_ITEMS_BACKUP_1 }}'
    S3_SECRET_CLOUD_ITEMS_BACKUP_2='{{ .Values.S3_SECRET_CLOUD_ITEMS_BACKUP_2 }}'
    SECURE_AUTH_KEY='{{ .Values.SECURE_AUTH_KEY }}'
    SECURE_AUTH_SALT='{{ .Values.SECURE_AUTH_SALT }}'
    WP_DEBUG_LOG=true
    WP_ENV='{{ .Values.WP_ENV }}'
    WP_HOME='{{ .Values.WP_HOME }}'
    WP_SITEURL='{{ .Values.WP_SITEURL }}'
    JWT_PRIVATE_KEY='{{ .Values.JWT_PRIVATE_KEY | b64enc }}'
    JWT_PUBLIC_KEY='{{ .Values.JWT_PUBLIC_KEY | b64enc }}'

