apiVersion: v1
kind: Secret
metadata:
  name: .env
  namespace: cloud-server
stringData:
  ADMIN_USER: {{ .Values.ADMIN_USER }}
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD }}
  ADMIN_EMAIL: {{ .Values.ADMIN_EMAIL }}
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN }}
  .env: |
    DB_HOST='{{ .Values.DB_HOST }}'
    DB_NAME='{{ .Values.DB_NAME }}'

    DB_USER='{{ .Values.DB_USER }}'
    DB_PASSWORD='{{ .Values.DB_PASSWORD }}'

    DB_PREFIX='{{ .Values.DB_PREFIX }}'

    WP_ENV='{{ .Values.WP_ENV }}'
    WP_HOME='{{ .Values.WP_HOME }}'
    WP_SITEURL="${WP_HOME}/wp"
    WP_DEBUG_LOG=logs/debug.log

    AUTH_KEY='{{ .Values.AUTH_KEY }}'
    SECURE_AUTH_KEY='{{ .Values.SECURE_AUTH_KEY }}'
    LOGGED_IN_KEY='{{ .Values.LOGGED_IN_KEY }}'
    NONCE_KEY='{{ .Values.NONCE_KEY }}'

    AUTH_SALT='{{ .Values.AUTH_SALT }}'
    SECURE_AUTH_SALT='{{ .Values.SECURE_AUTH_SALT }}'
    LOGGED_IN_SALT='{{ .Values.LOGGED_IN_SALT }}'
    NONCE_SALT='{{ .Values.NONCE_SALT }}'
