apiVersion: v1
kind: Secret
metadata:
  name: wp-config
  namespace: cloud-server
stringData:
  ADMIN_USER: {{ .Values.ADMIN_USER }}
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD }}
  ADMIN_EMAIL: {{ .Values.ADMIN_EMAIL }}
  wp-config.php: |
    <?php
    define( 'DB_NAME', '{{ .Values.DB_NAME }}' );
    define( 'DB_USER', '{{ .Values.DB_USER }}' );
    define( 'DB_PASSWORD', '{{ .Values.DB_PASSWORD }}' );
    define( 'DB_HOST', '{{ .Values.DB_HOST }}' );
    define( 'DB_CHARSET', 'utf8' );
    define( 'DB_COLLATE', '' );

    define( 'AUTH_KEY', '{{ .Values.AUTH_KEY }}' );
    define( 'SECURE_AUTH_KEY', '{{ .Values.SECURE_AUTH_KEY }}' );
    define( 'LOGGED_IN_KEY', '{{ .Values.LOGGED_IN_KEY }}' );
    define( 'NONCE_KEY', '{{ .Values.NONCE_KEY }}' );
    define( 'AUTH_SALT', '{{ .Values.AUTH_SALT }}' );
    define( 'SECURE_AUTH_SALT', '{{ .Values.SECURE_AUTH_SALT }}' );
    define( 'LOGGED_IN_SALT', '{{ .Values.LOGGED_IN_SALT }}' );
    define( 'NONCE_SALT', '{{ .Values.NONCE_SALT }}' );

    if ( false !== strpos( getenv( 'VIRTUAL_HOST' ), 'staging' ) ) {
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
    }

    define( 'WP_ALLOW_MULTISITE', true );
    define( 'MULTISITE', true );
    define( 'SUBDOMAIN_INSTALL', false );
    $base = '/api';
    define( 'DOMAIN_CURRENT_SITE', getenv( 'VIRTUAL_HOST' ) );
    define( 'PATH_CURRENT_SITE', '/api' );
    define( 'SITE_ID_CURRENT_SITE', 1 );
    define( 'BLOG_ID_CURRENT_SITE', 1 );

    /* That's all, stop editing! Happy blogging. */

    /** Absolute path to the WordPress directory. */
    if ( ! defined( 'ABSPATH' ) ) {
      define( 'ABSPATH', dirname( __FILE__ ) . '/' );
    }

    /** Sets up WordPress vars and included files. */
    require_once ABSPATH . 'wp-settings.php';
