DB_NAME:
DB_USER:
DB_PASSWORD:
DB_HOST:
DB_PREFIX:

AUTH_KEY:
SECURE_AUTH_KEY:
LOGGED_IN_KEY:
NONCE_KEY:
AUTH_SALT:
SECURE_AUTH_SALT:
LOGGED_IN_SALT:
NONCE_SALT:

ADMIN_USER:
ADMIN_PASSWORD:
ADMIN_EMAIL:

CLOUD_SERVER_IMAGE: 'elegantthemes/cloud-server:0.0.5'
VIRTUAL_HOST:
INSTALL_PATH:

GITHUB_TOKEN:
CLOUD_SERVER_REPO_URL:
WP_ENV:
WP_HOME:
WP_SITEURL:
