DB_NAME:
DB_USER:
DB_PASSWORD:
DB_HOST:

AUTH_KEY:
SECURE_AUTH_KEY:
LOGGED_IN_KEY:
NONCE_KEY:
AUTH_SALT:
SECURE_AUTH_SALT:
LOGGED_IN_SALT:
NONCE_SALT:

ADMIN_USER:
ADMIN_PASSWORD:
ADMIN_EMAIL:

VIRTUAL_HOST:
VIRTUAL_ROOT:

CLOUD_SERVER_REPO_URL:
GITHUB_TOKEN:
