apiVersion: apps/v1
kind: Deployment
metadata:
  name: percona-xtradb-cluster-operator
  labels:
    {{ .Values.label_name }}: {{ .Values.label_value }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: percona-xtradb-cluster-operator
  template:
    metadata:
      labels:
        name: percona-xtradb-cluster-operator
        {{ .Values.label_name }}: {{ .Values.label_value }}
    spec:
      serviceAccountName: percona-xtradb-cluster-operator
      containers:
        - name: percona-xtradb-cluster-operator
          image: percona/percona-xtradb-cluster-operator:1.4.0
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - percona-xtradb-cluster-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "percona-xtradb-cluster-operator"
