apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dc-screenshot
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections  1024;
    }

    http {
        include      /etc/nginx/mime.types;
        default_type application/octet-stream;

        server_names_hash_bucket_size  128;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log error;

        sendfile    on;
        tcp_nopush  on;
        tcp_nodelay on;

        disable_symlinks off;
        proxy_read_timeout 300;

        client_body_buffer_size 50M;
        client_max_body_size 100M;

        upstream php {
            server 127.0.0.1:9000;
        }

        # Redirect IP requests to the domain
        server {
            listen 80;
            server_name _;

            return 301 http://cloud-screenshot.dc-screenshot.svc.cluster.local$request_uri;
        }

        server {
            listen 80;
            server_name cloud-screenshot.dc-screenshot.svc.cluster.local;

            root /srv/cloud-screenshot/web;
            index index.html index.htm index.php;

            location ~ ([^/]*)sitemap(.*)\.x(m|s)l$ {
                ## this redirects sitemap.xml to /sitemap_index.xml
                rewrite ^/sitemap\.xml$ /sitemap_index.xml permanent;

                ## this makes the XML sitemaps work
                rewrite ^/([a-z]+)?-?sitemap\.xsl$ /index.php?xsl=$1 last;
                rewrite ^/sitemap_index\.xml$ /index.php?sitemap=1 last;
                rewrite ^/([^/]+?)-sitemap([0-9]+)?\.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;
            }

            if (!-e $request_filename) {
                rewrite /wp-admin$ $scheme://$host$uri/ permanent;
                rewrite ^(/[^/]+)?(/wp-.*) $2 last;
                rewrite ^(/[^/]+)?(/.*\.php) $2 last;
            }

            location / {
                try_files $uri $uri/ /index.php?$args;
            }

            location ~* ^.+\.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
                access_log off; log_not_found off; expires 1d;
            }

            location ~ [^/]\.php(/|$) {
                fastcgi_index index.php;
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
                fastcgi_read_timeout 60;
                fastcgi_pass php;
            }

            location /healthz {
                access_log off;
                return 200;
            }
        }
    }
