apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: dc-screenshot
stringData:
  ADMIN_USER: {{ .Values.ADMIN_USER }}
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD }}
  ADMIN_EMAIL: {{ .Values.ADMIN_EMAIL }}
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN }}
  UPLOADS_ZIP_URL: {{ .Values.UPLOADS_ZIP_URL | squote }}
  .env: |
    AUTH_KEY={{ .Values.AUTH_KEY | squote }}
    AUTH_SALT={{ .Values.AUTH_SALT | squote }}
    CLOUD_SCREENSHOT_PATH={{ .Values.INSTALL_PATH | squote }}
    CLOUD_SCREENSHOT_REPO_URL={{ .Values.CLOUD_SCREENSHOT_REPO_URL | squote }}
    DB_HOST_0={{ .Values.DB_HOST_0 | squote }}
    DB_HOST_1={{ .Values.DB_HOST_1 | squote }}
    DB_HOST_2={{ .Values.DB_HOST_2 | squote }}
    DB_NAME={{ .Values.DB_NAME | squote }}
    DB_PASSWORD={{ .Values.DB_PASSWORD | squote }}
    DB_PREFIX={{ .Values.DB_PREFIX | squote }}
    DB_USER={{ .Values.DB_USER | squote }}
    IMAGE_VERSION={{ .Values.CLOUD_SCREENSHOT_VERSION | squote }}
    LOGGED_IN_KEY={{ .Values.LOGGED_IN_KEY | squote }}
    LOGGED_IN_SALT={{ .Values.LOGGED_IN_SALT | squote }}
    NONCE_KEY={{ .Values.NONCE_KEY | squote }}
    NONCE_SALT={{ .Values.NONCE_SALT | squote }}
    S3_BUCKET_CLOUD_ITEMS={{ .Values.S3_BUCKET_CLOUD_ITEMS | squote }}
    S3_BUCKET_CLOUD_ITEMS_BACKUP_1={{ .Values.S3_BUCKET_CLOUD_ITEMS_BACKUP_1 | squote }}
    S3_BUCKET_CLOUD_ITEMS_BACKUP_2={{ .Values.S3_BUCKET_CLOUD_ITEMS_BACKUP_2 | squote }}
    S3_ENDPOINT_CLOUD_ITEMS={{ .Values.S3_ENDPOINT_CLOUD_ITEMS | squote }}
    S3_ENDPOINT_CLOUD_ITEMS_BACKUP_1={{ .Values.S3_ENDPOINT_CLOUD_ITEMS_BACKUP_1 | squote }}
    S3_ENDPOINT_CLOUD_ITEMS_BACKUP_2={{ .Values.S3_ENDPOINT_CLOUD_ITEMS_BACKUP_2 | squote }}
    S3_KEY_CLOUD_ITEMS={{ .Values.S3_KEY_CLOUD_ITEMS | squote }}
    S3_KEY_CLOUD_ITEMS_BACKUP_1={{ .Values.S3_KEY_CLOUD_ITEMS_BACKUP_1 | squote }}
    S3_KEY_CLOUD_ITEMS_BACKUP_2={{ .Values.S3_KEY_CLOUD_ITEMS_BACKUP_2 | squote }}
    S3_REGION_CLOUD_ITEMS={{ .Values.S3_REGION_CLOUD_ITEMS | squote }}
    S3_REGION_CLOUD_ITEMS_BACKUP_1={{ .Values.S3_REGION_CLOUD_ITEMS_BACKUP_1 | squote }}
    S3_REGION_CLOUD_ITEMS_BACKUP_2={{ .Values.S3_REGION_CLOUD_ITEMS_BACKUP_2 | squote }}
    S3_SECRET_CLOUD_ITEMS={{ .Values.S3_SECRET_CLOUD_ITEMS | squote }}
    S3_SECRET_CLOUD_ITEMS_BACKUP_1={{ .Values.S3_SECRET_CLOUD_ITEMS_BACKUP_1 | squote }}
    S3_SECRET_CLOUD_ITEMS_BACKUP_2={{ .Values.S3_SECRET_CLOUD_ITEMS_BACKUP_2 | squote }}
    SECURE_AUTH_KEY={{ .Values.SECURE_AUTH_KEY | squote }}
    SECURE_AUTH_SALT={{ .Values.SECURE_AUTH_SALT | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}
    WP_DEBUG_LOG=true
    WP_ENV={{ .Values.WP_ENV | squote }}
    WP_HOME={{ .Values.WP_HOME | squote }}
    WP_SITEURL={{ .Values.WP_SITEURL | squote }}

