apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      containers:
        - name: autoscaler
          image: {{ .Values.image | quote }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
          env:
            - name: LINODE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: LINODE_TOKEN
            - name: RANCHER_REGISTRATION_COMMAND
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: RANCHER_REGISTRATION_COMMAND
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: autoscaler-config
              mountPath: /config
              readOnly: true
            - name: autoscaler-source
              mountPath: /srv
      volumes:
        - name: autoscaler-config
          secret:
            secretName: {{ .Values.secretName }}
        - name: autoscaler-source
          emptyDir: {}
