# Default values for percona-xtradb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

s3_bucket_name:
s3_credentials_secret_name:
s3_endpoint:
s3_region:
cluster_name:
secrets_name:
ssl_secrets_name:
ssl_internal_secrets_name:
storage_class_name:
vault_secrets_name:
