BOTS_SERVER_IMAGE:
GIT_BASE_URL:
INGRESS_CLASS_NAME: traefik
REPLICAS: 1
VIRTUAL_HOST:

TOKEN:
SECRET:
TF_NOTIFY_TOKEN:
ZENHUB_KEY:
SLACK_TOKEN:
ET_API_KEY:
ET_USERNAME:

SOURCE_SSH_PRIVATE_KEY:
SOURCE_SSH_CONFIG:
