apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ai-server
  namespace: dai-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/limit-rps: "3"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-req-status-code: "429"
    nginx.ingress.kubernetes.io/limit-conn-status-code: "429"
    nginx.ingress.kubernetes.io/use-regex: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.VIRTUAL_HOST }}
      secretName: ai-server-tls
  rules:
    - host: {{ .Values.VIRTUAL_HOST }}
      http:
        paths:
          - path: /
            backend:
              serviceName: ai-server
              servicePort: 9999
