apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: dai-app
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN }}
  .env: |
    AI_SERVER_ENV={{ .Values.AI_SERVER_ENV | squote }}
    AI_SERVER_PATH={{ .Values.INSTALL_PATH | squote }}
    AI_SERVER_REPO_URL={{ .Values.AI_SERVER_REPO_URL | squote }}
    COOKIE_SALT={{ .Values.COOKIE_SALT | squote }}
    IMAGE_VERSION={{ .Values.AI_SERVER_VERSION | squote }}
    JWT_ACCESS_TOKEN_EXPIRES_IN={{ .Values.JWT_ACCESS_TOKEN_EXPIRES_IN | squote }}
    JWT_REFRESH_TOKEN_EXPIRES_IN={{ .Values.JWT_REFRESH_TOKEN_EXPIRES_IN | squote }}
    JWT_PRIVATE_KEY={{ .Values.JWT_PRIVATE_KEY | b64enc | squote }}
    JWT_PUBLIC_KEY={{ .Values.JWT_PUBLIC_KEY | b64enc | squote }}
    OPENAI_API_KEY={{ .Values.OPENAI_API_KEY | squote }}
    REDIS_HOSTNAME={{ .Values.REDIS_HOSTNAME | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}

