apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote }}
  .env: |
    AI_SERVER_ENV={{ .Values.AI_SERVER_ENV | squote }}
    AI_SERVER_PATH={{ .Values.INSTALL_PATH | squote }}
    AI_SERVER_REPO_URL={{ .Values.AI_SERVER_REPO_URL | squote }}
    AWS_ACCESS_KEY_ID={{ .Values.AWS_ACCESS_KEY_ID | squote }}
    AWS_SECRET_ACCESS_KEY={{ .Values.AWS_SECRET_ACCESS_KEY | squote }}
    AWS_REGION={{ .Values.AWS_REGION | squote }}
    IMAGE_VERSION={{ .Values.AI_SERVER_VERSION | squote }}
    INTERNAL_TOKEN={{ .Values.INTERNAL_TOKEN | squote }}
    JWT_ACCESS_TOKEN_EXPIRES_IN={{ .Values.JWT_ACCESS_TOKEN_EXPIRES_IN | squote }}
    JWT_REFRESH_TOKEN_EXPIRES_IN={{ .Values.JWT_REFRESH_TOKEN_EXPIRES_IN | squote }}
    JWT_PRIVATE_KEY={{ .Values.JWT_PRIVATE_KEY | b64enc | squote }}
    JWT_PUBLIC_KEY={{ .Values.JWT_PUBLIC_KEY | b64enc | squote }}
    OPENAI_API_KEY={{ .Values.OPENAI_API_KEY | squote }}
    BACKUP_OPENAI_API_KEYS={{ .Values.BACKUP_OPENAI_API_KEYS | squote }}
    REDIS_HOSTNAME={{ .Values.REDIS_HOSTNAME | squote }}
    STABLE_DIFFUSION_FALLBACK_API_KEY={{ .Values.STABLE_DIFFUSION_FALLBACK_API_KEY | squote }}
    STABLE_DIFFUSION_API_KEY={{ .Values.STABLE_DIFFUSION_API_KEY | squote }}
    STABLE_DIFFUSION_API_KEYS={{ .Values.STABLE_DIFFUSION_API_KEYS | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}

