apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.REPLICAS }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        redis-client: 'true'
    spec:
      containers:
        - name: {{ .Release.Name }}
          env:
            - name: GIT_BASE_URL
              value: {{ .Values.GIT_BASE_URL | squote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.VIRTUAL_HOST | squote }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
          image: {{ .Values.BOTS_SERVER_IMAGE | squote }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 3
          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: source-ssh
              mountPath: /root/.ssh
              readOnly: true
      volumes:
        - name: source-ssh
          secret:
            secretName: {{ .Release.Name }}-source-ssh
            defaultMode: 0400
