apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Release.Namespace }}
stringData:
  TOKEN: {{ .Values.TOKEN | squote }}
  SECRET: {{ .Values.SECRET | squote }}
  TF_NOTIFY_TOKEN: {{ .Values.TF_NOTIFY_TOKEN | squote }}
  ZENHUB_KEY: {{ .Values.ZENHUB_KEY | squote }}
  SLACK_TOKEN: {{ .Values.SLACK_TOKEN | squote }}
  ET_API_KEY: {{ .Values.ET_API_KEY | squote }}
  et_api_key: {{ .Values.ET_API_KEY | squote }}
  ET_USERNAME: {{ .Values.ET_USERNAME | squote }}
  et_username: {{ .Values.ET_USERNAME | squote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-source-ssh
  namespace: {{ .Release.Namespace }}
stringData:
  id_rsa: |
{{ .Values.SOURCE_SSH_PRIVATE_KEY | indent 4 }}
  config: |
{{ .Values.SOURCE_SSH_CONFIG | indent 4 }}
