affinity: {}
clusterRoleName: gha-runner-autoscaler
configMapName: gha-runner-autoscaler
dryRun: true
image: elegantthemes/gha-runner-autoscaler:26.7.15
imageVersion: 0.1.2
secretName: gha-runner-autoscaler

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

scaleDownEnabled: false

monitoring:
  enabled: false
  clusterName: unknown
  scrapeInterval: 30s
  manualReviewAlertFor: 5m
  runbookUrl: https://github.com/elegantthemes/gha-runner-autoscaler#manual-review-alert
