affinity: {}
clusterRoleName: gha-runner-autoscaler
configMapName: gha-runner-autoscaler
image: elegantthemes/gha-runner-autoscaler:26.7.15
secretName: gha-runner-autoscaler

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
