AUTH_SERVER_PORT:
AUTH_SERVER_IMAGE:
AUTH_SERVER_REPO_URL:
AUTH_SERVER_VERSION:
ENV_FILE:
GITHUB_TOKEN:
GIT_REF:
INGRESS_CLASS_NAME: traefik
INSTALL_PATH:
MEMORY_LIMIT:
REPLICAS:
UPTIME_MONITOR_TOKEN:
VIRTUAL_HOST:
